In [8]:
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re

In [9]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

In [10]:
def create_df_from_json(direc):
    """
    This function loops through all json file in a particular sub-directory
    of `data` directory.
    Converts them into a pandas dataframe.
    Returns the dataframe.
    """
    df_merged = pd.DataFrame()
    pat = direc + '_([a-z]+_?[a-z]+_*[a-z]+)*(.json$)'
    prog = re.compile(pat)
    directory = r'data/' + direc
    for file in os.scandir(directory):
        if(file.path.endswith('.json')):
            with open(file, encoding='utf-8') as f:
                d = json.load(f)
                result = prog.match(file.name)
                tag = result.group(1)
                if len(d['results']) == 0:
                    df = pd.DataFrame.from_dict({'results': [0]})
                else:
                    df = pd.DataFrame.from_dict(d['results'])
                df['tag'] = tag
                if 'next_page_token' in d.keys():
                    df['next_page_token'] = d['next_page_token']
                else:
                    df['next_page_token'] = None
                if d['status'] == 'ZERO_RESULTS':
                    df['no_of_results'] = 0
                else:
                    df['no_of_results'] = len(d['results']) 
        if df_merged.empty:
            df_merged = df
        else:
            df_merged = pd.concat([df_merged, df], axis=0, ignore_index=True)
    df_merged.to_csv('data/csv/' + direc + '.csv')
    return df_merged

In [5]:
with open('data/aurangabad/aurangabad_tourist_attraction_3.json', encoding='utf-8') as f:
    d = json.load(f)
    awb = pd.DataFrame.from_dict(d['results'])
    awb.to_csv('data/csv/awb.csv')

In [7]:
len(awb)

60

In [11]:
df = create_df_from_json('aurangabad')

In [4]:
df_awb = pd.read_csv('data/csv/aurangabad.csv')
df_goa = pd.read_csv('data/csv/goa.csv')

In [17]:
df_awb.head()

,Unnamed: 0,business_status,formatted_address,geometry,icon,id,name,photos,place_id,plus_code,rating,reference,types,user_ratings_total,tag,next_page_token,no_of_results,permanently_closed,opening_hours,price_level,results
0,0,OPERATIONAL,"Jalna Road, Chilkalthana, Aurangabad, Maharash...","{'location': {'lat': 19.8673554, 'lng': 75.395...",https://maps.gstatic.com/mapfiles/place_api/ic...,a53e86388fea52c932d85371d900a95960108792,Aurangabad Airport,"[{'height': 3000, 'html_attributions': ['<a hr...",ChIJh3bjGgej2zsRZp59kcFhQGc,"{'compound_code': 'V98W+W8 Chilkalthana, Auran...",4.2,ChIJh3bjGgej2zsRZp59kcFhQGc,"['airport', 'point_of_interest', 'establishment']",795.0,airport,NaN,1,NaN,NaN,NaN,NaN
1,1,CLOSED_TEMPORARILY,"BACKSIDE OF PATEL LAWNS, H.NO137 P.NO37 ABRAR ...","{'location': {'lat': 19.8547242, 'lng': 75.310...",https://maps.gstatic.com/mapfiles/place_api/ic...,05998676f9b31acff3f79d329f302e496d8a3cc7,AR.PLAY,"[{'height': 719, 'html_attributions': ['<a hre...",ChIJJ6eJVXGZ2zsRTy25c7Nbe_o,"{'compound_code': 'V836+V3 Aurangabad, Maharas...",0.0,ChIJJ6eJVXGZ2zsRTy25c7Nbe_o,"['amusement_park', 'point_of_interest', 'estab...",0.0,amusement_park,NaN,20,True,NaN,NaN,NaN
2,2,OPERATIONAL,"3-8-286, Sanjay Nagar, Mondha, Aurangabad, Mah...","{'location': {'lat': 19.8827237, 'lng': 75.344...",https://maps.gstatic.com/mapfiles/place_api/ic...,76f886219c249e672087355cd08f1025960d1cbc,Sk Sadabahar Amusement park,NaN,ChIJx9z5l4ij2zsRKtJSO-QPaoY,"{'compound_code': 'V8MV+3P Mondha, Aurangabad,...",0.0,ChIJx9z5l4ij2zsRKtJSO-QPaoY,"['home_goods_store', 'point_of_interest', 'sto...",0.0,amusement_park,NaN,20,NaN,NaN,NaN,NaN
3,3,CLOSED_TEMPORARILY,"NH 211, Vitkheda - Ellora Rd, near Daulatabad,...","{'location': {'lat': 19.9558, 'lng': 75.222134...",https://maps.gstatic.com/mapfiles/place_api/ic...,d493796bd0c6e29983ca2b82b29b4c5c5a4c876a,H2O Waterpark,"[{'height': 720, 'html_attributions': ['<a hre...",ChIJTcHd0RmR2zsRz8H3-JTVsGw,"{'compound_code': 'X64C+8V Daulatabad, Maharas...",3.8,ChIJTcHd0RmR2zsRz8H3-JTVsGw,"['amusement_park', 'point_of_interest', 'estab...",756.0,amusement_park,NaN,20,True,NaN,NaN,NaN
4,4,CLOSED_TEMPORARILY,"Daulatabad, Maharashtra 431002, India","{'location': {'lat': 19.9528817, 'lng': 75.222...",https://maps.gstatic.com/mapfiles/place_api/ic...,98c4f7aba6977e00ceabb3596973cd3951edee4a,Deluxe Green Valley,"[{'height': 3456, 'html_attributions': ['<a hr...",ChIJ9W3noL-R2zsRrGsB7whC2qQ,"{'compound_code': 'X63F+55 Daulatabad, Maharas...",4.0,ChIJ9W3noL-R2zsRrGsB7whC2qQ,"['amusement_park', 'point_of_interest', 'estab...",5.0,amusement_park,NaN,20,True,NaN,NaN,NaN

In [16]:
df_goa.head()

,Unnamed: 0,business_status,formatted_address,geometry,icon,id,name,opening_hours,photos,place_id,plus_code,rating,reference,types,user_ratings_total,tag,next_page_token,no_of_results,permanently_closed,results,price_level
0,0,OPERATIONAL,"Airport Rd, Dabolim, Goa 403801, India","{'location': {'lat': 15.3803485, 'lng': 73.834...",https://maps.gstatic.com/mapfiles/place_api/ic...,59156bf796e0b356f3a18a7b05256b86813f7ad5,Goa International Airport,{'open_now': True},"[{'height': 2280, 'html_attributions': ['<a hr...",ChIJTfgMjPrHvzsRV3U0LSIp1Lc,"{'compound_code': '9RJM+4X Dabolim, Goa', 'glo...",3.7,ChIJTfgMjPrHvzsRV3U0LSIp1Lc,"['airport', 'point_of_interest', 'establishment']",4348.0,airport,NaN,1,NaN,NaN,NaN
1,1,OPERATIONAL,"Calangute-Anjuna Main Road, Padre Agnel Vaddo,...","{'location': {'lat': 15.579003, 'lng': 73.7587...",https://maps.gstatic.com/mapfiles/place_api/ic...,799588f102efa93ac261f0d95d0b1b3fc000cf35,Splashdown Waterpark,{},"[{'height': 720, 'html_attributions': ['<a hre...",ChIJMS8RWSXqvzsRD_BatlAomOk,"{'compound_code': 'HQH5+JG Anjuna, Goa', 'glob...",3.7,ChIJMS8RWSXqvzsRD_BatlAomOk,"['tourist_attraction', 'amusement_park', 'poin...",1146.0,amusement_park,NaN,9,NaN,NaN,NaN
2,2,OPERATIONAL,"Padi, Goa 403703, India","{'location': {'lat': 15.0893788, 'lng': 74.056...",https://maps.gstatic.com/mapfiles/place_api/ic...,7092aacd672c2a963b81e47c0fc281bfc58564d2,Nagesh Jungle Resort,NaN,"[{'height': 2400, 'html_attributions': ['<a hr...",ChIJLZDpFL5RvjsRyRdfAtsHfVs,"{'compound_code': '33Q4+QP Maina, Goa', 'globa...",3.6,ChIJLZDpFL5RvjsRyRdfAtsHfVs,"['amusement_park', 'point_of_interest', 'estab...",118.0,amusement_park,NaN,9,NaN,NaN,NaN
3,3,OPERATIONAL,"Quepem Market Road, Nirmal Nagar, Xeldem, Goa ...","{'location': {'lat': 15.2377093, 'lng': 74.076...",https://maps.gstatic.com/mapfiles/place_api/ic...,0641ee70c2f984d7d876e0d696cf69bf1954ab1a,6 Shades Of Nature,{'open_now': True},"[{'height': 4608, 'html_attributions': ['<a hr...",ChIJk1VOXR2tvzsRBYY5TB4bVgI,"{'compound_code': '63QG+3G Xeldem, Goa', 'glob...",3.9,ChIJk1VOXR2tvzsRBYY5TB4bVgI,"['amusement_park', 'point_of_interest', 'estab...",404.0,amusement_park,NaN,9,NaN,NaN,NaN
4,4,OPERATIONAL,"Gudi, Quepem Rd, Chandor, Goa 403714, India","{'location': {'lat': 15.2423522, 'lng': 74.032...",https://maps.gstatic.com/mapfiles/place_api/ic...,ac63d04d3c04be2f4988d5163fececca7464cad5,Nagesh Love Forest,{'open_now': False},"[{'height': 1173, 'html_attributions': ['<a hr...",ChIJNShtiX6tvzsRfW6eUqD5Xtc,"{'compound_code': '62RM+W2 Chandor, Goa', 'glo...",3.6,ChIJNShtiX6tvzsRfW6eUqD5Xtc,"['tourist_attraction', 'amusement_park', 'poin...",261.0,amusement_park,NaN,9,NaN,NaN,NaN

In [7]:
df_awb.iloc[0]['geometry']

"{'location': {'lat': 19.8673554, 'lng': 75.39579599999999}, 'viewport': {'northeast': {'lat': 19.86897092989272, 'lng': 75.3971448798927}, 'southwest': {'lat': 19.86627127010728, 'lng': 75.39444522010727}}}"

In [18]:
df_awb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          506 non-null    int64
 1   business_status     491 non-null    object
 2   formatted_address   495 non-null    object
 3   geometry            495 non-null    object
 4   icon                495 non-null    object
 5   id                  495 non-null    object
 6   name                495 non-null    object
 7   photos              372 non-null    object
 8   place_id            495 non-null    object
 9   plus_code           480 non-null    object
 10  rating              492 non-null    float64
 11  reference           495 non-null    object
 12  types               495 non-null    object
 13  user_ratings_total  492 non-null    float64
 14  tag                 506 non-null    object
 15  next_page_token     440 non-null    object
 16  no_of_results       506 non-null    int64
 17  permanently_closed  274 non-null    object
 18  opening_hours       156 non-null    object
 19  price_level         35 non-null     float64
 20  results             11 non-null     float64
dtypes: float64(4), int64(2), object(15)
memory usage: 83.1+ KB

In [20]:
df_awb_cleaned = df_awb.drop(['Unnamed: 0', 'formatted_address', 'icon', 
                             'id', 'photos', 'reference', 'next_page_token',],
                            axis=1)

In [21]:
df_awb_cleaned.head()

,business_status,geometry,name,place_id,plus_code,rating,types,user_ratings_total,tag,no_of_results,permanently_closed,opening_hours,price_level,results
0,OPERATIONAL,"{'location': {'lat': 19.8673554, 'lng': 75.395...",Aurangabad Airport,ChIJh3bjGgej2zsRZp59kcFhQGc,"{'compound_code': 'V98W+W8 Chilkalthana, Auran...",4.2,"['airport', 'point_of_interest', 'establishment']",795.0,airport,1,NaN,NaN,NaN,NaN
1,CLOSED_TEMPORARILY,"{'location': {'lat': 19.8547242, 'lng': 75.310...",AR.PLAY,ChIJJ6eJVXGZ2zsRTy25c7Nbe_o,"{'compound_code': 'V836+V3 Aurangabad, Maharas...",0.0,"['amusement_park', 'point_of_interest', 'estab...",0.0,amusement_park,20,True,NaN,NaN,NaN
2,OPERATIONAL,"{'location': {'lat': 19.8827237, 'lng': 75.344...",Sk Sadabahar Amusement park,ChIJx9z5l4ij2zsRKtJSO-QPaoY,"{'compound_code': 'V8MV+3P Mondha, Aurangabad,...",0.0,"['home_goods_store', 'point_of_interest', 'sto...",0.0,amusement_park,20,NaN,NaN,NaN,NaN
3,CLOSED_TEMPORARILY,"{'location': {'lat': 19.9558, 'lng': 75.222134...",H2O Waterpark,ChIJTcHd0RmR2zsRz8H3-JTVsGw,"{'compound_code': 'X64C+8V Daulatabad, Maharas...",3.8,"['amusement_park', 'point_of_interest', 'estab...",756.0,amusement_park,20,True,NaN,NaN,NaN
4,CLOSED_TEMPORARILY,"{'location': {'lat': 19.9528817, 'lng': 75.222...",Deluxe Green Valley,ChIJ9W3noL-R2zsRrGsB7whC2qQ,"{'compound_code': 'X63F+55 Daulatabad, Maharas...",4.0,"['amusement_park', 'point_of_interest', 'estab...",5.0,amusement_park,20,True,NaN,NaN,NaN

In [24]:
df_awb_cleaned['business_status'].value_counts()

CLOSED_TEMPORARILY    274
OPERATIONAL           217
Name: business_status, dtype: int64

In [23]:
df_awb_cleaned[df_awb_cleaned['tag'] == 'movie_theater']

,business_status,geometry,name,place_id,plus_code,rating,types,user_ratings_total,tag,no_of_results,permanently_closed,opening_hours,price_level,results
314,OPERATIONAL,"{'location': {'lat': 19.8848645, 'lng': 75.325...",Khinvasara Cineplex (Amba Apsara),ChIJUxhDCSSZ2zsR0DwM6PPPQCQ,"{'compound_code': 'V8MG+W4 Aurangpura, Auranga...",3.6,"['movie_theater', 'point_of_interest', 'establ...",1295.0,movie_theater,3,NaN,{'open_now': True},NaN,NaN
315,CLOSED_TEMPORARILY,"{'location': {'lat': 19.8338682, 'lng': 75.248...",Sai Ram Engineers C-189 M.I.D.C Waluj Aurangabad,ChIJ_x8vmhuZ2zsRi0eJx3WQAS0,"{'compound_code': 'R6MX+GG Waluj, Aurangabad, ...",5.0,"['movie_theater', 'point_of_interest', 'establ...",1.0,movie_theater,3,True,NaN,NaN,NaN
316,OPERATIONAL,"{'location': {'lat': 19.87953, 'lng': 75.38284...",Harman Finochem Ltd,ChIJsaH7k-Oi2zsRVl6ObecGSfU,"{'compound_code': 'V9HM+R4 Aurangabad, Maharas...",4.1,"['health', 'point_of_interest', 'establishment']",15.0,movie_theater,3,NaN,{'open_now': True},NaN,NaN

In [11]:
df_awb['tag'].value_counts()

stadium               20
amusement_park        20
hindu_temple          20
campground            20
gas_station           20
library               20
lodging               20
police                20
aquarium              20
hospital              20
museum                20
spa                   20
bar                   20
bus_station           20
mosque                20
tourist_attraction    20
church                20
park                  20
atm                   20
restaurant            20
night_club            20
bakery                20
cafe                  20
taxi_stand            12
shopping_mall         10
movie_theater          3
zoo                    2
embassy                2
book_store             2
art_gallery            2
light_rail_station     1
rv_park                1
bowling_alley          1
train_station          1
meal_delivery          1
transit_station        1
casino                 1
liquor_store           1
car_rental             1
synagogue              1
subway_station         1
airport                1
meal_takeaway          1
Name: tag, dtype: int64

In [20]:
df.columns

Index(['business_status', 'formatted_address', 'geometry', 'icon', 'id',
       'name', 'photos', 'place_id', 'plus_code', 'rating', 'reference',
       'types', 'user_ratings_total', 'tag', 'next_page_token',
       'no_of_results', 'permanently_closed', 'opening_hours', 'price_level',
       'results'],
      dtype='object')

In [14]:
df_awb['next_page_token'].value_counts().size

22

In [29]:
df[['rating', 'user_ratings_total', 'name']].sort_values(by=['rating', 'user_ratings_total'], ascending=[False, False])[:20]

     rating  user_ratings_total                                        name
462     5.0                11.0                   Shree Aurangabad Property
231     5.0                 7.0  Jyoti Maternity Home And Sonography Clinic
148     5.0                 5.0             BaseCamp - Backpackers Campsite
311     5.0                 5.0                             Tawakkal Masjid
446     5.0                 5.0                           GODS OWN AYURCARE
36      5.0                 4.0         Betta Fish Store By Barwal Aquarium
324     5.0                 4.0                                Minar E Aman
30      5.0                 3.0            Manohar Fish Palace (Aquarium) 🐠
52      5.0                 3.0                           Saraswat Bank ATM
263     5.0                 3.0                             Papyrus Library
269     5.0                 3.0                         Achievers Abhyasika
378     5.0                 3.0              Police Headquarters Aurangabad
189     5.0                 2.0                          Muthoot Forex Ltd.
213     5.0                 2.0                           Jogeshwari temple
224     5.0                 2.0                           Shree Datt Mandir
297     5.0                 2.0                             Amanulla masjid
313     5.0                 2.0                               Gausia Masjid
334     5.0                 2.0                           Pravin R. Nawathe
394     5.0                 2.0                              Police Station
459     5.0                 2.0                     Cidco diagnostic centre

In [21]:
d = pd.DataFrame.from_dict(d['result'].items())

In [23]:
d

,0,1
0,address_components,"[{'long_name': 'Jalna Road', 'short_name': 'Ja..."
1,adr_address,"Shop No. 19 &amp; 20, Radhika Arcade, Near Nup..."
2,business_status,OPERATIONAL
3,formatted_address,"Shop No. 19 & 20, Radhika Arcade, Near Nupur T..."
4,formatted_phone_number,070207 47417
5,geometry,"{'location': {'lat': 19.875231, 'lng': 75.3541..."
6,icon,https://maps.gstatic.com/mapfiles/place_api/ic...
7,id,2ab13cb55f576a9aead7a77d34539d79deffb2ab
8,international_phone_number,+91 70207 47417
9,name,Food-de-Bollywood
10,photos,"[{'height': 720, 'html_attributions': ['<a hre..."
11,place_id,ChIJ0W8rZpCi2zsR9miRCE6PmcQ
12,plus_code,"{'compound_code': 'V9G3+3M Aurangabad, Maharas..."
13,price_level,2
14,rating,4.2
15,reference,ChIJ0W8rZpCi2zsR9miRCE6PmcQ
16,reviews,"[{'author_name': 'Daisy Tran', 'author_url': '..."
17,scope,GOOGLE
18,types,"[restaurant, food, point_of_interest, establis..."
19,url,https://maps.google.com/?cid=14166511668184574198
20,user_ratings_total,311
21,utc_offset,330
22,vicinity,"Shop No. 19 & 20, Radhika Arcade, Near Nupur T..."

In [27]:
df.iloc[0]

business_status                                             OPERATIONAL
formatted_address     Shop No. 19 & 20, Radhika Arcade, Near Nupur T...
geometry              {'location': {'lat': 19.875231, 'lng': 75.3541...
icon                  https://maps.gstatic.com/mapfiles/place_api/ic...
id                             2ab13cb55f576a9aead7a77d34539d79deffb2ab
name                                                  Food-de-Bollywood
photos                [{'height': 4608, 'html_attributions': ['<a hr...
place_id                                    ChIJ0W8rZpCi2zsR9miRCE6PmcQ
plus_code             {'compound_code': 'V9G3+3M Aurangabad, Maharas...
price_level                                                           2
rating                                                              4.2
reference                                   ChIJ0W8rZpCi2zsR9miRCE6PmcQ
types                 [restaurant, food, point_of_interest, establis...
user_ratings_total                                                  311
opening_hours                                                       NaN
permanently_closed                                                  NaN
Name: 0, dtype: object

In [2]:
df.iloc[0]['geometry']

NameError: name 'df' is not defined